#!/bin/bash

# Script: Fibonacci.sh
# Purpose: Generate Fibonacci sequence

#Special for n=1
if [ $# -eq 1 ]
then
        Num=$1
else
#Give user to choose the Nth Fibonacci sequence
        echo -n "Choose n:"
        read Num

fi
#Set the first 2 Fibonacci sequence to be 1
f1=1
f2=1

echo "The Fibonacci sequence for n equal $Num is:"

for (( i=1;i<=Num;i++ ))
do

        echo -n "$f1 "
        fn=$((f1+f2))
        f1=$f2
        f2=$fn
done     
          
         
echo    
~                                                                                              
~               
